# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sitemap_generator}
  s.version = "0.2.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Adam Salter", "Karl Varga"]
  s.date = %q{2010-03-18}
  s.description = %q{Install as a plugin or Gem to easily generate ['enterprise-class'][enterprise_class] Google Sitemaps for your Rails site, using a simple 'Rails Routes'-like DSL and a single rake task.}
  s.email = %q{kjvarga@gmail.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "lib/sitemap_generator.rb",
     "lib/sitemap_generator/helper.rb",
     "lib/sitemap_generator/link.rb",
     "lib/sitemap_generator/link_set.rb",
     "lib/sitemap_generator/mapper.rb",
     "lib/sitemap_generator/tasks.rb",
     "rails/install.rb",
     "rails/uninstall.rb",
     "tasks/sitemap_generator_tasks.rake",
     "templates/sitemap.rb",
     "templates/sitemap_index.builder",
     "templates/xml_sitemap.builder"
  ]
  s.homepage = %q{http://github.com/kjvarga/sitemap_generator}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Generate 'enterprise-class' Sitemaps for your Rails site using a simple 'Rails Routes'-like DSL and a single Rake task}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

