source 'http://rubygems.org'

gem 'sitemap_generator', :path => '../../'

gem 'rails', '2.3.8'
gem 'rspec', '1.3.0', :require => 'spec'
gem 'rspec-rails', '~>1.3.2', :require => 'spec/rails'
gem 'sqlite3-ruby', '1.3.1', :require => 'sqlite3'
gem 'ruby-debug', '0.10.3'
gem 'ruby-debug-base', '0.10.3'
gem 'mocha', '0.9.10'
gem 'nokogiri', '1.4.4'