source 'http://rubygems.org'

gem 'rails', '3.0.0'
gem "rspec-rails", ">= 2.0.0.rc"
gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'sitemap_generator', :path => '../../'
gem 'nokogiri'
gem 'yaml_db'

group :test do
  platforms :ruby_18 do
    gem 'ruby-debug', '=0.10.3'
    gem 'ruby-debug-base', '=0.10.3'
  end
end