source 'https://rubygems.org'

gem 'rails', '~> 6.1'

# group :test do
  # gem 'minitest' # https://github.com/rspec/rspec-rails/issues/758
  # gem 'debugger', :require => nil
  # gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'combustion'
gem 'nokogiri'
gem 'rspec-rails'
gem 'sitemap_generator', :path => '../../'
gem 'sqlite3'
gem 'byebug'
# end
